### ISSUE TITLE
sarama.MockBroker error with sarama-cluster

### ISSUE THREAD

**Issue by jvrmaia** [bsm/sarama-cluster#166]
Hi,

I'm using sarama-cluster here and wanna test my app using [sarama.MockBroker](https://github.com/Shopify/sarama/blob/master/mockbroker.go) to mock Kafka but apparently sarama-cluster can't work with it. 

Error returned after `cluster.NewConsumer(...)`:
```
kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

does anyone can help me understand why?

thks

Example:
```
func TestSubscriber(t *testing.T) {
	broker0 := sarama.NewMockBroker(t, 0)
	var testMsg = sarama.StringEncoder("Foo")
	mockFetchResponse := sarama.NewMockFetchResponse(t, 1)
	for i := 0; i < 10; i++ {
		mockFetchResponse.SetMessage("test", 0, int64(i+1234), testMsg)
	}
	broker0.SetHandlerByMap(map[string]sarama.MockResponse{
		"MetadataRequest": sarama.NewMockMetadataResponse(t).
			SetBroker(broker0.Addr(), broker0.BrokerID()).
			SetLeader("test", 0, broker0.BrokerID()),
		"OffsetRequest": sarama.NewMockOffsetResponse(t).
			SetOffset("test", 0, sarama.OffsetOldest, 0).
			SetOffset("test", 0, sarama.OffsetNewest, 2345),
		"FetchRequest": mockFetchResponse,
	})
	conf := cluster.NewConfig()
	conf.Consumer.Return.Errors = true
	conf.Group.Return.Notifications = true
	conf.Group.PartitionStrategy = "range"

	c, err := cluster.NewConsumer([]string{broker0.Addr()}, "test", []string{"test"}, conf)
	defer c.Close()
	if err != nil {
		t.Log(err)
	}
	for i := 0; i < 10; i++ {
		select {
		case message, _ := <-c.Messages():
			assert.Equal(t, message, testMsg)
		case err := <-c.Errors():
			t.Error(err)
		}
	}
	broker0.Close()
}
```
Error: 
```
=== RUN   TestSubscriber
--- FAIL: TestSubscriber (150.76s)
	kafka_test.go:35: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x6c3706]

goroutine 6 [running]:
testing.tRunner.func1(0xc420075380)
	/.../.gvm/gos/go1.8.3/src/testing/testing.go:622 +0x29d
panic(0x7aed40, 0x9fbf10)
	/.../.gvm/gos/go1.8.3/src/runtime/panic.go:489 +0x2cf
.../vendor/github.com/bsm/sarama-cluster.(*Consumer).Close(0x0, 0x820146, 0x4)
	/.../vendor/github.com/bsm/sarama-cluster/consumer.go:195 +0x26
panic(0x7aed40, 0x9fbf10)
	/.../.gvm/gos/go1.8.3/src/runtime/panic.go:489 +0x2cf
.../subscriber/kafka.TestSubscriber(0xc420075380)
	/.../subscriber/kafka/kafka_test.go:39 +0xa67
testing.tRunner(0xc420075380, 0x8358c8)
	/.../.gvm/gos/go1.8.3/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/.../.gvm/gos/go1.8.3/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	b2winc.com/ragnarok/subscriber/kafka	150.762s
```

`/.../subscriber/kafka/kafka_test.go:39 ` is `case message, _ := <-c.Messages():`

**Comment by eapache** [comment]
Your setup looks approximately right to me? Though I believe your mock broker will also need to handle some join-group messages or something like that? The consumer-group API is complicated.

**Comment by dim** [comment]
Unfortunately, that's correct, I doubt that it will work with the current MockBroker implementation. Sorry, closing, as this isn't really a sarama-cluster issue per se.

**Comment by jvrmaia** [comment]
any advice to unit test withou running kafka?

**Comment by dim** [comment]
We usually create an interface to match `custer.Consumer` and create a mock for unit testing. Would that work for you?

**Comment by jvrmaia** [comment]
ok, I'll try change here
tks

**Comment by dim** [comment]
@SimpleApp no, it doesn't as there are too many variables in terms of how the users might want to use that. Most people only need `Messages() <-chan *sarama.ConsumerMessage` and `MarkOffset(msg *sarama.ConsumerMessage, metadata string)` but there is quite a bit of variety with `Partitions()`, `Errors()` etc.

A simple example could look like this:
```
type MyConsumer interface {
  Messages() <-chan *sarama.ConsumerMessage
  MarkOffset(*sarama.ConsumerMessage, string)
  Close() error
}

type mockConsumer struct { ch chan *sarama.ConsumerMessage }

func NewMockConsumer(msgs []*sarama.ConsumerMessage) MyConsumer {
  ch := make(chan *sarama.ConsumerMessage, len(msgs))
  for _, m := range msgs {
    ch <- m
  }
  return &mockConsumer{ch: ch}
}

func (m *mockConsumer) Messages() <-chan *sarama.ConsumerMessage { return m.ch }
func (m *mockConsumer) MarkOffset(*sarama.ConsumerMessage, string) { }
func (m *mockConsumer) Close() error {  return nil }
```

**Comment by SimpleApp** [comment]
@dim Thanks for the snippet. Maybe you could include this code somewhere in the examples folder then. It's still a nice thing to have lying around, if only to be used as a starting point for something more complex.

**Comment by natdm** [comment]
FYI, this does not handle `Errors()` which is `Errors() <-chan error` on cluster and `Errors() chan *sarama.ConsumerError` on sarama. 🤦‍♂️
