### ISSUE TITLE
'kafka-consumer-groups.sh --describe' throw exception

### ISSUE THREAD

**Issue by liaojianqi** [bsm/sarama-cluster#192]
my kafka version is kafka_2.11-0.10.1.1

I run code:
`
package main

import (
    "fmt"
    "github.com/bsm/sarama-cluster"
    "os/signal"
    "os"
    "log"
)

func test() {
    // init (custom) config, enable errors and notifications
    config := cluster.NewConfig()
    config.Consumer.Return.Errors = true
    config.Group.Return.Notifications = true

    // init consumer
    brokers := []string{"127.0.0.1:8410"}
    topics := []string{"cluster1"}
    consumer, err := cluster.NewConsumer(brokers, "cluster-group", topics, config)
    if err != nil {
        panic(err)
    }
    defer consumer.Close()

    // trap SIGINT to trigger a shutdown.
    signals := make(chan os.Signal, 1)
    signal.Notify(signals, os.Interrupt)

    // consume errors
    go func() {
        for err := range consumer.Errors() {
            log.Printf("Error: %s\n", err.Error())
        }
    }()

    // consume notifications
    go func() {
        for ntf := range consumer.Notifications() {
            log.Printf("Rebalanced: %+v\n", ntf)
        }
    }()

    // consume messages, watch signals
    for {
        select {
        case msg, ok := <-consumer.Messages():
            if ok {
                fmt.Fprintf(os.Stdout, "%s/%d/%d\t%s\t%s\n", msg.Topic, msg.Partition, msg.Offset, msg.Key, msg.Value)
                consumer.MarkOffset(msg, "") // mark message as processed
            }
        case <-signals:
            return
        }
    }
}

func main() {
    go func() {
        test()
    }()
    test()
}
`

as you see, I create TWO consumers
then I cd into kafka/bin and run:
`./kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:8410 --describe --group cluster-group`
then it throw a exception:
`Error while executing consumer group command Error reading field 'version': java.nio.BufferUnderflowException
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'version': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
	at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeAssignment(ConsumerProtocol.java:106)
	at kafka.admin.AdminClient$$anonfun$describeConsumerGroup$1.apply(AdminClient.scala:156)
	at kafka.admin.AdminClient$$anonfun$describeConsumerGroup$1.apply(AdminClient.scala:155)
	at scala.collection.immutable.List.map(List.scala:277)
	at kafka.admin.AdminClient.describeConsumerGroup(AdminClient.scala:155)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describeGroup(ConsumerGroupCommand.scala:308)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$class.describe(ConsumerGroupCommand.scala:89)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describe(ConsumerGroupCommand.scala:296)
	at kafka.admin.ConsumerGroupCommand$.main(ConsumerGroupCommand.scala:68)
	at kafka.admin.ConsumerGroupCommand.main(ConsumerGroupCommand.scala)`

And I found that:
only when the amount of consumer more than the amount of (partitions * topics), this exception will throw.
for example, if there are two consumer, one topic and two partition, it will not throw exception.
if there are two consumer, one topic and one partition, it will throw exception.

and I want to know what cause this exception?
Is it a bug of sarama-cluster or kafka?
thank you.

**Comment by dim** [comment]
It looks like problem in Kafka to be honest, but please make sure that you set the right version in your `config := cluster.NewConfig()` https://github.com/Shopify/sarama/blob/master/utils.go#L147. Please also try a later kafka version, it may be a known issue
